version: '3.9'
services:

  datacollector:
    build: .
    ports:
      - 8080:8080
    networks:
      - nlp-network
    container_name: datacollector
    restart: always
    environment:
      JAVA_OPTS: "-XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=90.0"
    depends_on:
      - flyway

  flyway:
    image: flyway/flyway:6.4.0-alpine
    command: -url=jdbc:postgresql://db:5432/sampledb -schemas=public -user=postgres -password=docker -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - nlp-network
    depends_on:
      - db

  db:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    networks:
      - nlp-network
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: sampledb
      SCHEMA: public
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: postgres
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  nlp-network:
    driver: bridge