window_size: 5
vector_size: 100
movie_lines: ../../../data/1_raw/movies/movie_lines.txt
movie_conversations: ../../../data/1_raw/movies/movie_conversations.txt
blog_directory: ../../../data/1_raw/blogs
encoded_blog_directory: ../../data/encoded_blogs
pretrained_embeddings: ../../../glove.6B/glove.6B.100d.txt
stop_words: stop_words.txt
cbow:
  epochs: 5
skip_gram:
  epochs: 5